### ISSUE TITLE
Music Disc does not stop ambient music from playing

### ISSUE THREAD

**Issue by c-leri** [GlowSand/ostoverhaul#10]
Playing a music disk does stop any currently playing ambient music but it does not prevent a new ambient track from playing.
I don't know if this is intentional or due to limitations or just a bug.

**Comment by GlowSand** [comment]
I couldn't replicate this do you think you could get me your mod list, maybe a video showing this in action?

**Comment by GlowSand** [comment]
Closing as cannot be replicated + the author hasn't replied 👍

**Comment by c-leri** [comment]
oh shoot sorry I hadn't seen your answer i'll try to replicate it again and tell you if I manage to do it

**Comment by c-leri** [comment]
I was actually able to replicate this bug consistently with the [music duration rducer](https://github.com/LudoCrypt/Music-Duration-Reducer) mod.
So what happens is that when I play a first disk it won't be overlapped by ambient music but if I play another disk after this first one it will be overlapped by ambient music each time, even if you cut the first disk directly after starting playing it.
I don't know if I'm being clear but you can try it yourself and you should be able to replicate this bug to
