### ISSUE TITLE
Background music plays in the middle of records

### ISSUE THREAD

**Issue by foul-fortune-feline** [GlowSand/ostoverhaul#2]
The point of making the bgm stop playing when you start a record is defeated if it starts up a quarter of the way through, and that's ~90% of what I downloaded the mod for.

**Comment by foul-fortune-feline** [comment]
Charm has a similar functionality that might be worth looking into implementing

**Comment by GlowSand** [comment]
Just tested and confirmed this issue, sorry for the inconvenience, will be fixed next update!

**Comment by foul-fortune-feline** [comment]
Cool cool, thanks!

**Comment by GlowSand** [comment]
It's been a while but fixed in the latest 1.18 release https://modrinth.com/mod/ost-overhaul/version/P32Hsu2f
(only on modrinth will upload to curseforge whenever its back up)
