### ISSUE TITLE
Ost overhaul crashed, v1.18.1 with modpack.

### ISSUE THREAD

**Issue by GreenSPTM** [GlowSand/ostoverhaul#7]
---- Minecraft Crash Report ----

Time: 4/6/22, 8:21 PM
Description: Unexpected error

java.lang.ClassCastException: class java.util.HashMap cannot be cast to class com.google.gson.internal.LinkedTreeMap (java.util.HashMap is in module java.base of loader 'bootstrap'; com.google.gson.internal.LinkedTreeMap is in unnamed module of loader 'app')
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at glowsand.ostoverhaul.OstOverhaulConfig.getMusicToPlay(OstOverhaulConfig.java:233)
	at glowsand.ostoverhaul.client.OverhaulMusicTracker.playRandomSound(OverhaulMusicTracker.java:235)
	at glowsand.ostoverhaul.client.OverhaulMusicTracker.playRandomSound(OverhaulMusicTracker.java:230)
	at glowsand.ostoverhaul.client.OverhaulMusicTracker.playMusicOrSmthn(OverhaulMusicTracker.java:200)
	at glowsand.ostoverhaul.client.OverhaulMusicTracker.tick(OverhaulMusicTracker.java:89)
	at net.minecraft.client.sound.MusicTracker.handler$cmk000$tickmixin(MusicTracker:534)
	at net.minecraft.client.sound.MusicTracker.tick(MusicTracker)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1759)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1086)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$cmc000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:18046)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:760)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at glowsand.ostoverhaul.OstOverhaulConfig.getMusicToPlay(OstOverhaulConfig.java:233)
	at glowsand.ostoverhaul.client.OverhaulMusicTracker.playRandomSound(OverhaulMusicTracker.java:235)
	at glowsand.ostoverhaul.client.OverhaulMusicTracker.playRandomSound(OverhaulMusicTracker.java:230)
	at glowsand.ostoverhaul.client.OverhaulMusicTracker.playMusicOrSmthn(OverhaulMusicTracker.java:200)
	at glowsand.ostoverhaul.client.OverhaulMusicTracker.tick(OverhaulMusicTracker.java:89)
	at net.minecraft.class_1142.handler$cmk000$tickmixin(class_1142.java:534)
	at net.minecraft.class_1142.method_18669(class_1142.java)

-- Affected level --
Details:
	All players: 1 total; [class_746['Jaez'/758, l='ClientLevel', x=177.24, y=125.00, z=500.42]]
	Chunk stats: 1024, 243
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,76,160), Section: (at 0,12,0 in 3,4,10; chunk contains blocks 48,-64,160 to 63,319,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2084078 game time, 60443 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$cmc000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:18046)
	at net.minecraft.class_310.method_1514(class_310.java:760)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, alternate-leaves-mod-1-18.zip, Green.Spectrum(MC resourcepack).zip, ! )9FA_pew's )6OVERLAYS )9Pack, STONEBORN+-+1.18+-+V3.1.zip, Fabric Mods, visualoverhaul/fancyfurnace, continuity/default, illuminations/pixelaccurate, continuity/glass_pane_culling_fix, visualoverhaul/coloredwaterbucket, visualoverhaul/nobrewingbottles, betterbeds/fancybeds, armorchroma/alternative-icons, __MoreMcmeta Internal__

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2209315688 bytes (2106 MiB) / 3959422976 bytes (3776 MiB) up to 4194304000 bytes (4000 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4610M CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 2.99
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 4600
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x0416
	Graphics card #0 versionInfo: DriverVersion=20.19.15.4835
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 10323.89
	Virtual memory used (MB): 8596.45
	Swap memory total (MB): 2226.46
	Swap memory used (MB): 195.42
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx4000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		amecsapi: Amecs API 1.3.6+mc1.18-pre1
		animatica: Animatica 0.4+1.18
		appleskin: AppleSkin mc1.18-2.2.0
		architectury: Architectury 3.7.38
		armorchroma: Armor Chroma 1.2.1
		bedrockify: BedrockIfy 1.4.0+mc1.18.1
		betterbeds: Better Beds 1.2.0
		betterf3: BetterF3 1.2.2
		bettermounthud: Better Mount HUD 1.1.4
		betterthirdperson: Better Third Person 1.6.0
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		bobby: Bobby 3.1.0
		brb: Better Recipe Book 1.5.6
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.6.55
		caffeineconfig: CaffeineConfig 1.0.0
		cameraoverhaul: Camera Overhaul 1.3.0-fabric-universal
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cavedust: Cave Dust 1.2.0
		chat_heads: Chat Heads 0.6.0
		citresewn: CIT Resewn 1.0.1+1.18.2
		citresewn-defaults: CIT Resewn: Defaults 1.0.1+1.18.2
		cleardespawn: Clear Despawn 21w40a-1.1.3
		clickthrough: ClickThrough 1.18-fabric0.43.1-0.4
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		cloth-config-lite: cloth-config-lite 2.0.6
		coat: Coat 1.0.0-beta.17+mc1.18-pre1
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		com_ishland_c2me_libs_: libs 0.2.0+alpha.6.55
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		continuity: Continuity 1.1.0+1.18
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cullleaves: Cull Leaves 2.3.2
		cursormod: Custom Cursor Mod 1.3.1
		custom-fog: Custom Fog 2.1.0
		customsplashscreen: Custom Splash Screen 1.2.0
		dashloader: DashLoader 3.1.1+1.18
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.4.0
		dev_quantumfusion_hyphen: hyphen 0.2.0
		dontdropit: Don't Drop It! 2.3.8+1.18
		dsurround: Â§6Dynamic SurroundingsÂ§r: Â§eFabric Edition 0.0.4
		durabilityviewer: Giselbaers Durability Viewer 1.18-fabric0.43.1-1.10.2
		dynamicfps: Dynamic FPS 2.1.0
		dynmus: Dynamic Music 1.4.1
		easiervillagertrading: EasierVillagerTrading 1.18-fabric0.43.1-1.5.4
		easymagic: Easy Magic 3.2.1
		eatinganimationid: Eating Animation 1.5
		effective: Effective 1.1.1
		emojitype: Emoji Type 1.0.3
		enchantment_lore: Enchantment Lore 1.2.6-1
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.3+1.18
		enhancedblockentities: Enhanced Block Entities 0.5+1.18
		entity_texture_features: Entity Texture Features 2.6.0
		entityculling: EntityCulling-Fabric 1.5.0
		equipmentcompare: Equipment Compare 1.2.12
		extrasounds: Extra Sounds 2.2.1+1.18.2
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.3+d7c144a8d2
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabricloader: Fabric Loader 0.13.3
		fabulousclouds: Fabulous Clouds 0.3.0
		fallingleaves: Falling Leaves 1.9.0+1.18.1
		forgeconfigapiport: Forge Config API Port 3.1.1
		forgetmechunk: Forget Me Chunk 1.18.X-1.0.3
		gbfabrictools: GBfabrictools 1.3.4+1.17
		goosik-config: goosik-config 0.2.0
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.2
		immersive_hud: Immersive HUD 1.3-1.18.1-fabric
		indium: Indium 1.0.2-alpha3+mc1.18.1
		inspecio: Inspecio 1.2.1+1.18
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		itemborders: Item Borders 1.1.5
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kirin: Kirin UI 1.10.0-beta.2
		krypton: Krypton 0.1.9
		ksyxis: Ksyxis 1.1
		lambdabettergrass: LambdaBetterGrass 1.2.2+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazy-language-loader: lazy-language-loader 0.2.6
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.2.4
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.8
		memoryusagescreen: Memory Usage Screen 1.2
		merchantmarkers: Merchant Markers 1.1.2
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.1
		minimalmenu: MinimalMenu 1.18.1-0.1.0
		modmenu: Mod Menu 3.0.1
		monsters_in_the_closet: Monsters in the Closet 1.0.3+1.18
		moremcmeta: MoreMcmeta 1.18.1-3.0.2
		mousewheelie: Mouse Wheelie 1.8.8+mc1.18-pre5
		musicdr: Music Duration Reducer 1.0.0
		nostrip: No Strip 1.2.2-1.17+
		notenoughanimations: NotEnoughAnimations 1.5.0
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.1
		org_joml_joml: joml 1.10.2
		org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		ostoverhaul: Ost Overhaul 0.2.3
		petowner: Pet Owner 1.8.2-1.18-pre4+
		phosphor: Phosphor 0.8.1
		physicsmod: Physics Mod 2.6.7
		pickupnotifier: Pick Up Notifier 3.1.0
		presencefootsteps: Presence Footsteps 1.4.0
		pride: Pride Lib 1.1.0+1.17
		puzzleslib: Puzzles Lib 3.2.1
		quilt-loading-screen: Quilt Loading Screen 2.2.0+1.17
		reeses-sodium-options: Reese's Sodium Options 1.4.0
		sakurablossoms: Sakura Blossoms 1.0.2
		satin: Satin 1.7.0
		seamless_loading_screen: Seamless Loading Screen 1.3.6+1.18
		signtools: Sign Tools 1.0.0
		sleepwarp: SleepWarp 1.1.0+1.18.1
		smoothswapping: Smooth Swapping 0.4.4
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.4.0
		soundcategories: Sound Categories 1.2.1+1.18
		spruceui: SpruceUI 3.3.2+1.17
		tweed4_annotated: tweed4_annotated 1.3.0+mc1.18-pre2
		tweed4_base: tweed4_base 1.5.0+mc1.18-pre2
		tweed4_data: tweed4_data 1.2.1+mc1.18-pre2
		tweed4_data_hjson: tweed4_data_hjson 1.1.0+mc1.18-pre2
		tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18-pre2
		tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18-pre2
		visuality: Visuality 0.4.1
		visualoverhaul: VisualOverhaul 4.0.0
		visualworkbench: Visual Workbench 3.1.0
		vmp: Very Many Players 0.2.0+beta.3.8
		whyamionfire: Why Am I on Fire? 1.1.1
		wthit: wthit 4.5.5
		wthit-plugins: Wthit Plugins 1.0.4
	Launched Version: fabric-loader-0.13.3-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 4600 GL version 3.2.0 - Build 20.19.15.4835, Intel
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error' x 2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/alternate-leaves-mod-1-18.zip, file/Green.Spectrum(MC resourcepack).zip, file/! )9FA_pew's )6OVERLAYS )9Pack (incompatible), file/STONEBORN+-+1.18+-+V3.1.zip, Fabric Mods, visualoverhaul/fancyfurnace, continuity/default, illuminations/pixelaccurate, continuity/glass_pane_culling_fix, visualoverhaul/coloredwaterbucket, visualoverhaul/nobrewingbottles, betterbeds/fancybeds (incompatible), armorchroma/alternative-icons
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i7-4610M CPU @ 3.00GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Jaez'/758, l='ServerLevel[Test World]', x=177.24, y=125.00, z=500.42]]
	Data Packs: vanilla, Fabric Mods
	Client Crashes Since Restart: 2
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Ost Overhaul (ostoverhaul), Not Enough Crashes (notenoughcrashes)

**Comment by GlowSand** [comment]
Should be fixed in the latest 1.18.2 & 1.19 versions
